Feature/groups - first draft WIP
mynhiennguyen/loklok-clone pull request #9
Opened 2022-02-16 22:50 UTC by mynhiennguyen

**What was done?**
- addition of a simple select that allows the user to swap between groups (=canvases)
- adding group-info to all message types
- add new Action (`SendHistoryAction`) and Message (`changeGroup`) types to FE + BE
- rework BE to support Groups

**Next steps**
- let users dynamically add / delete / edit groups
- let users invite other users to groups... -> 'login' / authentication / identification needed?

2022-02-16 22:52 UTC, mynhiennguyen commented on be/server.ts
> +const groups = new Map<string, Group>([["Group A", new Group("Group A")], ["Group B", new Group("Group B")], ["Group C", new Group("Group C")]]);
currently hardcoded 3 groups - goal will be to have the user create / delete / edit their own groups

2022-02-16 22:53 UTC, mynhiennguyen commented on be/server.ts
> +    if(action instanceof SendHistoryAction){
this check seems odd 😓

2022-02-16 22:56 UTC, mynhiennguyen commented
**Question:** in order to have users invite other users to groups / manage group - some sort of login / authentication is needed? Any advice on how to approach this?

2022-03-02 11:12 UTC, Garbanas requested changes

2022-03-02 11:12 UTC, Garbanas commented on be/server.ts
> +  groups.get("Group A")?.historyStack.undoStack.forEach((m: Action) => {
Do not use "magic" strings (or numbers). When "Group A" is your default, denn add a constant somewhere like
```
const DEFAULT_GROUP_KEY = "Group A";
...
groups.get(DEFAULT_GROUP_KEY)?....
```

2022-03-02 11:12 UTC, Garbanas commented on be/src/types/action.ts
> +    public readonly group: string,
When you have a class "Group" with property "id: string", then better rename the parameter that has the group.id from "group" to "groupId" to be more specific. What if you wanted to pass the "Group" class?

2022-03-02 11:12 UTC, Garbanas commented on be/src/types/group.ts
> +    constructor(public readonly id: String) {
`public readonly id: String` can be `public readonly id: string`.
"String" is a class / object and "string" is a primitive

2022-03-02 11:12 UTC, Garbanas commented on be/src/types/group.ts
> +export class Group {
A group could have an ID (for internal use, sending as identifier) and a (display-)name (visible for humans).
So you could change the name of the group without affecting any history stack or message sending.

2022-03-16 07:30 UTC, merged